version: '2.1'
services:
  twitch-archiver:
    image: ronanraven/twitch-archiver:latest
    container_name: twitch-archiver
    volumes:
      - ./vods:/vods
    environment:
      - STR_APPID=
      - STR_APPSECRET=
      - JSON_CONFIG={"name":"jjamjim"}{"name":"theyed_","dir":"yed"}
    stop_grace_period: 1s
    restart: unless-stopped
